before_install:
  - sudo apt-get update
install:
  - pip install tox-travis codecov  # was pip3 earlier - changing to pip for 2.x
  - pip install -r requirements.txt # was pip3 earlier - changing to pip for 2.x
language:
  - python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
script:
  - flask run --cert=adhoc &
  - tox
